version: "3.7"
services:
  brave_browser:
    image: lscr.io/linuxserver/brave:latest
    container_name: myapps-brave
    security_opt:
      - seccomp:unconfined
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - UMASK=022
    volumes:
      - ${APP_DATA_DIR}/data:/config
    ports:
      - "3935:3001"
    devices:
      - "/dev/bus/usb:/dev/bus/usb"
    restart: unless-stopped
